### ISSUE TITLE
Should there be a Japanese README?

### ISSUE THREAD

**Issue by meowchanicyuumi** [karaoke-dev/karaoke#1264]
I understand that a lot of players will be speaking English when downloading/playing, but shouldn't there also be a Japanese language README, considering the game is based off of a Japanese pastime?

**Comment by andy840119** [comment]
Not really sure about that because eventually Lazer will have ruleset store, maybe can write different language of introduce in there.
Also, this repo/organization is focus on providing the source code to let anyone see how karaoke is actually working if they are interesting. So guess it's ok to just use english in here.

**Comment by meowchanicyuumi** [comment]
Okay, I didn't know there was gonna be a ruleset distribution place.
