### ISSUE TITLE
Not working, could be a mistake on download

### ISSUE THREAD

**Issue by MikangodJP** [karaoke-dev/karaoke#2071]
I just tried to install the mode to osu laser, and yeah I tried to run it and it is classical osu gameplay. Does it work on M1 Mac?
<img width="1440" alt="Screenshot 2023-07-17 at 10 58 28 PM" src="https://github.com/karaoke-dev/karaoke/assets/122189884/d5ecbbb7-1ca5-4a33-b8ec-47ce57e9c82e">

**Comment by MikangodJP** [comment]
<img width="1440" alt="Screenshot 2023-07-17 at 11 09 08 PM" src="https://github.com/karaoke-dev/karaoke/assets/122189884/e100eae1-cd5f-4844-8b34-ed9078d17d4d">
Some development, now I can't open the map but the gamemode itself looks like it is working. This changed after I used the mod in the gamemode... still don't know how to fix this and need help

**Comment by andy840119** [comment]
> Some development, now I can't open the map but the gamemode itself looks like it is working. This changed after I used the mod in the gamemode... still don't know how to fix this and need help

1. trying to download the `.zip` file instead of the `.dll` in the [release page](https://github.com/karaoke-dev/karaoke/releases/tag/2023.0716.0), un-zip and place all the file into the ruleset folder like how other ruleset did.
2. this ruleset does not support the beatmap conversion, means you need to download the beatmap for the karaoke ruleset(maybe [this](https://github.com/karaoke-dev/sample-beatmap/releases/tag/%E6%9E%AF%E3%82%8C%E3%81%AA%E3%81%84%E8%8A%B1) will work).

Also note that this ruleset is still under development and might have some bug that i haven't noticed or has no time to fix, so feel to ask and wait for the answer.

**Comment by MikangodJP** [comment]
For 1, I have downloaded all the .zip folder and unzipped them to paste all of them into the rulesets. And I also downloaded the bigger karaoke.dll file and stuffed it inside the ruleset folder.

The map in 2 works, its just the notes are not appearing and also the microphone is not connected.

**Comment by andy840119** [comment]
> And I also downloaded the bigger karaoke.dll file and stuffed it inside the ruleset folder.

No need to download this file if you already download the .zip

> ...its just the notes are not appearing and also the microphone is not connected.

It's expected if note and microphone is not working.
The final release of this ruleset will not be able to scoring because the scoring is not the first priority of this ruleset(let user able to create the beatmap in the editor is much more important than this).
User will be be able to create the beatmap with scoring feature in the editor.

**Comment by MikangodJP** [comment]
Alright, thanks. I will be looking forward for the features coming up.
Ask me for any help based on Japanese translations because I can speak Japanese.
See ya
