### ISSUE TITLE
Question - Running

### ISSUE THREAD

**Issue by Hexality** [karaoke-dev/karaoke#76]
Is it already possible to try this by building it myself?

**Comment by andy840119** [comment]
Of course!
But editor still not implemented yet, so you can try [sample beatmap](https://github.com/osu-Karaoke/sample-beatmap) or created by text editor.
If you can compile osu!, them you probably can compile this project.

**Comment by Hexality** [comment]
I can compile osu!lazer but when compiling this, osu!lazer refuses to load it

**Comment by andy840119** [comment]
I didn't use latest version of `osu.game` because it will cause crash in customize ruleset.
Use older version of `osu.game` might cause ruleset's `dll` cannot be imported.
.
I'll write a launcher next week, you can just compile launcher and run it, everything will be set-up.
If you have any question you can ask me in discord andy840119#8457.

**Comment by andy840119** [comment]
https://github.com/osu-Karaoke/osu-karaoke-launcher

Launcher has been created.
you can follow readme to compile and run this project.
